
services:
  postgres:
    image: postgres:latest
    networks:
      - bank-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminSecret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - udemy_simplebank_postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d simple_bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4
    networks:
      - bank-network
    ports: 
    - "8000:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminSecret
    volumes:
      - udemy_simplebank_pgadmin-data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bank-network
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://admin:adminSecret@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

volumes:
  udemy_simplebank_pgadmin-data:
      external: true
  udemy_simplebank_postgres-data:
      external: true

networks:
  bank-network:
    driver: bridge

