apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypta
spec:
  acme:
    email: {{ LETSENCRYPT_EMAIL }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-private-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx

